### ISSUE TITLE
java.lang.IllegalArgumentException: endRule without matching beginRule

### ISSUE THREAD

**Issue by anb0s** [anb0s/eclox#175]
eclipse.buildId=4.7.0.I20161208-0830
java.version=1.8.0_111
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -data file:/home/x/workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.committers.product

org.eclipse.core.jobs
Error
Thu Jan 19 19:40:06 CET 2017
An internal error occurred during: "Doxygen Build [/usr/bin/doxygen -b /eclox/eclox.ui/doc/eclox.ui.doxyfile]".

java.lang.IllegalArgumentException: endRule without matching beginRule: L/eclox/eclox.ui/doc/eclox.ui.doxyfile
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.jobs.ImplicitJobs.end(ImplicitJobs.java:114)
	at org.eclipse.core.internal.jobs.JobManager.endRule(JobManager.java:723)
	at eclox.core.doxygen.BuildJob.run(BuildJob.java:471)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Comment by anb0s** [comment]
Linux Debian test:
reproduced with 0.10.2.201606...
cannot reproduce with 0.11.0.v20161106-1459

**Comment by anb0s** [comment]
fixed with #177

**Comment by robross0606** [comment]
I am still getting this exception with eclox-0.11.0

	eclipse.buildId=4.6.2.M20161124-1400
	java.version=1.8.0_121
	java.vendor=Oracle Corporation
	BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
	Framework arguments:  -product org.eclipse.epp.package.jee.product
	Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

	Created Time: 2017-03-17 00:17:08.980

	org.eclipse.core.jobs
	Error
	Fri Mar 17 00:27:58 EDT 2017
	An internal error occurred during: "Doxygen Build [C:\Program Files\doxygen\bin\doxygen -b \Project\doc\doxygen\Doxyfile]".

	java.lang.IllegalArgumentException: endRule without matching beginRule: L/Project/doc/doxygen/Doxyfile
		at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
		at org.eclipse.core.internal.jobs.ImplicitJobs.end(ImplicitJobs.java:114)
		at org.eclipse.core.internal.jobs.JobManager.endRule(JobManager.java:706)
		at eclox.core.doxygen.BuildJob.run(BuildJob.java:493)
		at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by anb0s** [comment]
Thanks, i will investigate...

**Comment by anb0s** [comment]
Please check testing build from #188

**Comment by anb0s** [comment]
will be fixed with 0.11.1
